name: moor_fetcher
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  sqlite3_flutter_libs: ^0.2.0 
  moor: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
